### ISSUE TITLE
[FEATURE] Support for Create Tables with the REST API & SDK

### ISSUE THREAD

**Issue by slowder-bpcs** [databricks/databricks-sdk-py#256]
**Problem Statement**
Using the Unity Catalog SDK classes, you can create Metastores, Catalogs, and schemas.  But when you get to Tables, you can only delete, get, list, list_summaries, or update (the owner, nothing else). You can create functions with the SDK. You can create table constraints. But you cannot create tables. I also found you can't create tables via the REST API either. This seems like a basic thing; am I missing something?

**Proposed Solution**
In addition to the API/SDK, that would allow us at least to define our tables/views for our Unity catalogs. If we were to define a table that requires computing, we should have to spin up a cluster to perform that computing. 
**Additional Context**

 I'm building tools that allow users to migrate objects from hive metastores to Unity Catalog.  It'd be nice to complete these migrations from the SDK and not have to move to notebooks/jobs.

**Comment by mgyucht** [comment]
Thanks for raising this. I'll connect this to our UC team to see what they say about supporting create table in the REST API.

**Comment by mgyucht** [comment]
From the team: these APIs are not supported for customer use.  This is intentional because creating/updating a usable table typically requires extra actions by DBR (e.g., setting up the table's delta log in cloud storage).  The recommendation is for customers to use SQL to CREATE/ALTER tables in UC.

I would recommend taking a look at the [Databricks SQL connector](https://pypi.org/project/databricks-sql-connector/). You can use this to interact with UC tables from Python.

**Comment by slowder-bpcs** [comment]
OK. I started down that path while waiting to hear back. I'm building a tool to migrate tables from hive_metastore to UC.  I think I have it handling most every table case now.
